[package]
name = "guto/kart"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
signal = "sleitnick/signal@2.0.1"
knit = "sleitnick/knit@1.5.3"
promise = "evaera/promise@4.0.0"
janitor = "howmanysmall/janitor@1.15.6"